name: Unit tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          ninja-build \
          libcppunit-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libncurses-dev \
          liblua5.3-dev \
          lua5.3

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build and Test
      run: |
        meson setup build -Dtests=true -Dlua=enabled
        meson compile -C build
        meson test -C build

    - name: Archive test logs
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: build/meson-logs/testlog.txt

  ubuntu-variants:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config_flag: ["-Dxmlrpc-c=enabled -Dxmlrpc-tinyxml2=disabled", "-Dxmlrpc-c=disabled -Dxmlrpc-tinyxml2=enabled"]
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          ninja-build \
          libcppunit-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libncurses-dev \
          liblua5.3-dev \
          lua5.3

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        meson setup build -Dtests=true ${{ matrix.config_flag }}
        meson compile -C build

    - name: Test rtorrent
      run: meson test -C build

  macos:
    needs: ubuntu
    runs-on: macos-latest
    env:
      TEST_IGNORE_SIGNAL_INTERRUPT_LATENCY: "YES"
    steps:
    - name: Install Dependencies
      run: |
        brew install meson cppunit curl

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        meson setup build -Dtests=true
        meson compile -C build

    - name: Test rtorrent
      run: meson test -C build

  alpine:
    needs: ubuntu
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: ['x86_64']
    defaults:
      run:
        shell: alpine.sh {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        arch: ${{ matrix.platform }}
        packages: >
          build-base meson cppunit-dev curl-dev
          linux-headers ncurses-dev openssl-dev pkgconf zlib-dev
    - name: Build and Test
      run: |
        meson setup build -Dtests=true
        grep LT_SMP_CACHE_BYTES build/config.h
        meson compile -C build
        meson test -C build
